skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wallet_program = "6rAZLb32wv86p3uhqQQCZpDxn4BYiFBX7tqPvw7HpD27"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
