import devnet from './devnet.json'

/** Wrapped SOL: how native SOL takes part in token pools. */
export const WSOL_MINT = 'So11111111111111111111111111111111111111112'
export const WSOL_DECIMALS = 9

export interface SwapToken {
  /** Mint address. Native SOL is represented by WSOL_MINT. */
  mint: string
  symbol: string
  name: string
  decimals: number
}

export interface PoolConfig {
  pool: string
  mintA: string
  mintB: string
  lpMint: string
  vaultA: string
  vaultB: string
  feeBps: number
}

export interface DevnetConfig {
  programId: string
  /** Unix seconds when the program version that emits stealth announcements was deployed. */
  announcementsSince?: number
  tokens: SwapToken[]
  pools: PoolConfig[]
}

/**
 * Addresses of the deployed program and the pools/tokens created by scripts/seed-devnet.ts.
 * Regenerated by that script; do not edit by hand.
 */
export const DEVNET = devnet as DevnetConfig
